# Generated by Django 3.0.3 on 2020-07-17 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200717_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='alterado',
            new_name='changed',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='criado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publicado',
            new_name='published',
        ),
    ]
